[package]
name = "salvo-admin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { version = "0.68.4" }

tokio = { version = "1", features = ["macros"] }
#tracing = "0.1"
#tracing-subscriber = "0.3"

json = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
log4rs = "1.0"

rbs = { version = "4.5"}
rbatis = { version = "4.5", features = [] }
#rbatis = { version = "4.0",features = ["debug_mode"]}
rbdc-mysql={version="4.5"}

jsonwebtoken = "9.3.0"

redis = "0.25.3"

futures = { version = "0.3", default-features = false }
thiserror = "1.0"

once_cell = "1.18.0"
